package org.koghi.terranvm.entity;
// Generated 2/03/2011 03:36:38 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * Action generated by hbm2java
 */
@Entity
@Table(name="action"
    ,schema="public"
)
public class Action  implements java.io.Serializable {


     private int id;
     private int features;
     private String action;

    public Action() {
    }

    public Action(int id, int features, String action) {
       this.id = id;
       this.features = features;
       this.action = action;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="features", nullable=false)
    public int getFeatures() {
        return this.features;
    }
    
    public void setFeatures(int features) {
        this.features = features;
    }

    
    @Column(name="action", nullable=false)
    @NotNull
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }




}


