package org.koghi.terranvm.entity;

// Generated 24/05/2011 03:05:42 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * AsobancariaFormat generated by hbm2java
 */
@Entity
@Table(name = "asobancaria_format", schema = "public")
public class AsobancariaFormat implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String separator;
	private String checkIdentification;
	private int numberOfFooterLines;
	private int numberOfHeaderLines;
	private Set<AsobancariaItems> asobancariaItems;


	public AsobancariaFormat() {
	}

	public AsobancariaFormat(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public AsobancariaFormat(int id, String name, String separator, String checkIdentification, Set<AsobancariaItems> asobancariaItems, int numberOfFooterLines, int numberOfHeaderLines) {
		this.id = id;
		this.name = name;
		this.separator = separator;
		this.checkIdentification = checkIdentification;
		this.asobancariaItems = asobancariaItems;
		this.numberOfFooterLines = numberOfFooterLines;
		this.numberOfHeaderLines = numberOfHeaderLines;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "separator")
	public String getSeparator() {
		return this.separator;
	}

	public void setSeparator(String separator) {
		this.separator = separator;
	}
	
	@Column(name="check_identification", nullable=false)
    @NotNull
    public String getCheckIdentification() {
        return this.checkIdentification;
    }
    
    public void setCheckIdentification(String checkIdentification) {
        this.checkIdentification = checkIdentification;
    }
    
    @Column(name = "number_of_footer_lines", nullable = false)
	public int getNumberOfFooterLines() {
		return this.numberOfFooterLines;
	}

	public void setNumberOfFooterLines(int numberOfFooterLines) {
		this.numberOfFooterLines = numberOfFooterLines;
	}

	@Column(name = "number_of_header_lines", nullable = false)
	public int getNumberOfHeaderLines() {
		return this.numberOfHeaderLines;
	}

	public void setNumberOfHeaderLines(int numberOfHeaderLines) {
		this.numberOfHeaderLines = numberOfHeaderLines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "asobancariaFormat")
	public Set<AsobancariaItems> getAsobancariaItems() {
		return this.asobancariaItems;
	}

	public void setAsobancariaItems(Set<AsobancariaItems> asobancariaItems) {
		this.asobancariaItems = asobancariaItems;
	}

}
