package org.koghi.terranvm.entity;

// Generated 24/05/2011 03:05:42 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * AsobancariaField generated by hbm2java
 */
@Entity
@Table(name = "asobancaria_field", schema = "public")
public class AsobancariaField implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final int PK_PAYER_IDENTIFICATION = 1;
	public static final int PK_OFFICE = 2;
	public static final int PK_PAY_IDENTIFICATION = 3;
	public static final int PK_VALUE = 4;
	public static final int PK_DATE = 5;
	public static final int PK_TRANSACTION_TYPE = 6;
	
	private int id;
	private String name;
	private AsobancariaItems asobancariaItemses;

	public AsobancariaField() {
	}

	public AsobancariaField(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public AsobancariaField(int id, String name,
			AsobancariaItems asobancariaItemses) {
		this.id = id;
		this.name = name;
		this.asobancariaItemses = asobancariaItemses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "asobancariaField")
	public AsobancariaItems getAsobancariaItemses() {
		return this.asobancariaItemses;
	}

	public void setAsobancariaItemses(AsobancariaItems asobancariaItemses) {
		this.asobancariaItemses = asobancariaItemses;
	}

}
