package org.koghi.terranvm.entity;

// Generated 24/05/2011 03:05:42 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.NotNull;

/**
 * AsobancariaItems generated by hbm2java
 */
@Entity
@Table(name = "asobancaria_items", schema = "public")
public class AsobancariaItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private AsobancariaField asobancariaField;
	private AsobancariaFormat asobancariaFormat;
	private int iniPos;
	private Integer endPos;
	private int pos;

	public AsobancariaItems() {
	}

	public AsobancariaItems(AsobancariaField asobancariaField,
			AsobancariaFormat asobancariaFormat, int iniPos, int pos) {
		this.asobancariaField = asobancariaField;
		this.asobancariaFormat = asobancariaFormat;
		this.iniPos = iniPos;
		this.pos = pos;
	}

	public AsobancariaItems(AsobancariaField asobancariaField,
			AsobancariaFormat asobancariaFormat, int asobancariaFormat_1,
			int iniPos, Integer endPos, int pos) {
		this.asobancariaField = asobancariaField;
		this.asobancariaFormat = asobancariaFormat;
		this.iniPos = iniPos;
		this.endPos = endPos;
		this.pos = pos;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "asobancariaFormat"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "asobancaria_field", nullable = false)
	@NotNull
	public AsobancariaField getAsobancariaField() {
		return this.asobancariaField;
	}

	public void setAsobancariaField(AsobancariaField asobancariaField) {
		this.asobancariaField = asobancariaField;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "asobancaria_format", nullable = false)
	@NotNull
	public AsobancariaFormat getAsobancariaFormat() {
		return this.asobancariaFormat;
	}

	public void setAsobancariaFormat(AsobancariaFormat asobancariaFormat) {
		this.asobancariaFormat = asobancariaFormat;
	}

	@Column(name = "ini_pos", nullable = false)
	public int getIniPos() {
		return this.iniPos;
	}

	public void setIniPos(int iniPos) {
		this.iniPos = iniPos;
	}

	@Column(name = "end_pos")
	public Integer getEndPos() {
		return this.endPos;
	}

	public void setEndPos(Integer endPos) {
		this.endPos = endPos;
	}

	@Column(name = "pos", nullable = false)
	public int getPos() {
		return this.pos;
	}

	public void setPos(int pos) {
		this.pos = pos;
	}
}
