package org.koghi.terranvm.entity;

// Generated 2/05/2011 03:18:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AvaluationType generated by hbm2java
 */
@Entity
@Table(name = "avaluation_type", schema = "public")
public class AvaluationType implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Avaluation> avaluations = new HashSet<Avaluation>(0);

	public AvaluationType() {
	}

	public AvaluationType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public AvaluationType(int id, String name, Set<Avaluation> avaluations) {
		this.id = id;
		this.name = name;
		this.avaluations = avaluations;
	}

	@Id
	@SequenceGenerator(name = "pk_sequence", sequenceName = "avaluation_type_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "avaluationType")
	public Set<Avaluation> getAvaluations() {
		return this.avaluations;
	}

	public void setAvaluations(Set<Avaluation> avaluations) {
		this.avaluations = avaluations;
	}

}
