package org.koghi.terranvm.entity;

// Generated 2/05/2011 03:18:29 PM by Hibernate Tools 3.4.0.CR1

import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;

/**
 * Avaluation generated by hbm2java
 */
@Entity
@Table(name = "avaluation", schema = "public")
public class Avaluation implements java.io.Serializable {

	private int id;
	private Construction construction;
	private RealProperty realProperty;
	private AvaluationType avaluationType;
	private Date activationDate;
	private Date effectiveEndDate;
	private Double value1;
	private Double value2;
	private Double value3;
	private String scopeAvaluation;
	
	public Avaluation() {
	}

	public Avaluation(int id, AvaluationType avaluationType) {
		this.id = id;
		this.avaluationType = avaluationType;
	}

	public Avaluation(int id, Construction construction, RealProperty realProperty, AvaluationType avaluationType, Date activationDate, Date effectiveEndDate, Double value1, Double value2, Double value3, String scopeAvaluation) {
		this.id = id;
		this.construction = construction;
		this.realProperty = realProperty;
		this.avaluationType = avaluationType;
		this.activationDate = activationDate;
		this.effectiveEndDate = effectiveEndDate;
		this.value1 = value1;
		this.value2 = value2;
		this.value3 = value3;
		this.scopeAvaluation =scopeAvaluation;
	}

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "avaluation_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "construction")
	public Construction getConstruction() {
		return this.construction;
	}

	public void setConstruction(Construction construction) {
		this.construction = construction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "real_property")
	public RealProperty getRealProperty() {
		return this.realProperty;
	}

	public void setRealProperty(RealProperty realProperty) {
		this.realProperty = realProperty;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "avaluation_type", nullable = false)
	@NotNull
	public AvaluationType getAvaluationType() {
		return this.avaluationType;
	}

	public void setAvaluationType(AvaluationType avaluationType) {
		this.avaluationType = avaluationType;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "activation_date", length = 13)
	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_end_date", length = 13)
	public Date getEffectiveEndDate() {
		return this.effectiveEndDate;
	}

	public void setEffectiveEndDate(Date effectiveEndDate) {
		this.effectiveEndDate = effectiveEndDate;
	}

	@Column(name = "value_1", precision = 17, scale = 17)
	public Double getValue1() {
		return this.value1;
	}

	public void setValue1(Double value1) {
		this.value1 = value1;
	}
	

	@Column(name = "value_2", precision = 17, scale = 17)
	public Double getValue2() {
		return this.value2;
	}

	public void setValue2(Double value2) {
		this.value2 = value2;
	}

	@Column(name = "value_3", precision = 17, scale = 17)
	public Double getValue3() {
		return this.value3;
	}

	public void setValue3(Double value3) {
		this.value3 = value3;
	}
	
	//-------------------------------------
	
	@Transient
	public String getFormatterValue1(){
		if(this.getValue1() != null){
			NumberFormat formatter = new DecimalFormat("#,###.00");
			return formatter.format(getValue1());
		}else
			return null;
	}
	
	@Transient
	public void setFormatterValue1(String value){
		try{
			setValue1(Double.parseDouble(value));
		}catch (Exception e) {
			setValue1(0.0);
		}
	}
	
	@Transient
	public String getFormatterValue2(){
		if(this.getValue2() != null){
			NumberFormat formatter = new DecimalFormat("#,###.00");
			return formatter.format(getValue2());
		}else
			return null;
	}
	
	@Transient
	public void setFormatterValue2(String value){
		try{
			setValue2(Double.parseDouble(value));
		}catch (Exception e) {
			setValue2(0.0);
		}
	}
	
	@Transient
	public String getFormatterValue3(){
		if(this.getValue3() != null){
			NumberFormat formatter = new DecimalFormat("#,###.00");
			return formatter.format(getValue3());
		}else
			return null;
	}
	
	@Transient
	public void setFormatterValue3(String value){
		try{
			setValue3(Double.parseDouble(value));
		}catch (Exception e) {
			setValue3(0.0);
		}
	}
	
	
	

	//-------------------------------------
	
	
	
	
	
	
	

	@Column(name = "scope_avaluation")
	public String getScopeAvaluation() {
		return scopeAvaluation;
	}

	public void setScopeAvaluation(String scopeAvaluation) {
		this.scopeAvaluation = scopeAvaluation;
	}
	
	

}