package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * BusinessEntityType generated by hbm2java
 */
@Entity
@Table(name = "business_entity_type", schema = "public")
public class BusinessEntityType implements java.io.Serializable {

	private int id;
	private String nameBusinessEntityType;
	private String description;
	private Set<BusinessEntity> entities = new HashSet<BusinessEntity>(0);

	public BusinessEntityType() {
	}

	public BusinessEntityType(int id, String nameBusinessEntityType, String description) {
		this.id = id;
		this.nameBusinessEntityType = nameBusinessEntityType;
		this.description = description;
	}

	public BusinessEntityType(int id, String nameBusinessEntityType, String description, Set<BusinessEntity> entityTypes) {
		this.id = id;
		this.nameBusinessEntityType = nameBusinessEntityType;
		this.description = description;
		this.entities = entityTypes;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
		@SequenceGenerator(name = "pk_sequence", sequenceName = "business_entity_type_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getNameBusinessEntityType() {
		return this.nameBusinessEntityType;
	}

	public void setNameBusinessEntityType(String nameBusinessEntityType) {
		this.nameBusinessEntityType = nameBusinessEntityType;
	}

	@Column(name = "description", nullable = false)
	@NotNull
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(cascade={CascadeType.PERSIST, CascadeType.MERGE},
			mappedBy="entityTypes",
			targetEntity=BusinessEntity.class)
	public Set<BusinessEntity> getEntities() {
		return this.entities;
	}

	public void setEntities(Set<BusinessEntity> entityTypes) {
		this.entities = entityTypes;
	}

}
