package org.koghi.terranvm.entity;

// Generated 06-ene-2011 13:56:54 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.koghi.terranvm.entity.BusinessEntity;
import org.koghi.terranvm.entity.Project;
import org.hibernate.validator.NotNull;

/**
 * BusinessLine generated by hbm2java
 */
@Entity
@Table(name = "business_line", schema = "public")
public class BusinessLine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private BusinessEntity businessEntity;
	private BusinessLine businessLine;
	private String nameBusinessLine;
	private String costCenterBusinessLine;
	private Set<BusinessLine> businessLines = new HashSet<BusinessLine>(0);
	private Set<Project> projects = new HashSet<Project>(0);

	public BusinessLine() {
	}

	public BusinessLine(int id, BusinessEntity businessEntity, String nameBusinessLine, String costCenterBusinessLine) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.nameBusinessLine = nameBusinessLine;
		this.costCenterBusinessLine = costCenterBusinessLine;
	}

	public BusinessLine(int id, BusinessEntity businessEntity, BusinessLine businessLine, String nameBusinessLine, String costCenterBusinessLine, Set<BusinessLine> businessLines, Set<Project> projects) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.businessLine = businessLine;
		this.nameBusinessLine = nameBusinessLine;
		this.costCenterBusinessLine = costCenterBusinessLine;
		this.businessLines = businessLines;
		this.projects = projects;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "business_line_condition_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_unit")
	public BusinessEntity getBusinessEntity() {
		return this.businessEntity;
	}

	public void setBusinessEntity(BusinessEntity businessEntity) {
		this.businessEntity = businessEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent")
	public BusinessLine getBusinessLine() {
		return this.businessLine;
	}

	public void setBusinessLine(BusinessLine businessLine) {
		this.businessLine = businessLine;
	}

	@Column(name = "name_business_line", nullable = false)
	@NotNull
	public String getNameBusinessLine() {
		return this.nameBusinessLine;
	}

	public void setNameBusinessLine(String nameBusinessLine) {
		this.nameBusinessLine = nameBusinessLine;
	}

	@Column(name = "cost_center_business_line", nullable = false)
	@NotNull
	public String getCostCenterBusinessLine() {
		return this.costCenterBusinessLine;
	}

	public void setCostCenterBusinessLine(String costCenterBusinessLine) {
		this.costCenterBusinessLine = costCenterBusinessLine;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessLine", cascade = CascadeType.ALL)
	public Set<BusinessLine> getBusinessLines() {
		return this.businessLines;
	}

	public void setBusinessLines(Set<BusinessLine> businessLines) {
		this.businessLines = businessLines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "businessLine")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}
	
	@Transient
	public String getBusinessName(){
		return getBusinessEntity().getNameBusinessEntity();
	}

}
