package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


import org.hibernate.validator.NotNull;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "city", schema = "public")
public class City implements java.io.Serializable {

	private int id;
	private Region region;
	private String name;
	private String siigoCode;
	private Set<Address> addresses = new HashSet<Address>(0);	
	private Set<BusinessEntity> businessEntities = new HashSet<BusinessEntity>(0);
	

	public City() {
	}

	public City(int id, Region region, String name) {
		this.id = id;
		this.region = region;
		this.name = name;
	}

	public City(int id, Region region, String name, Set<Address> addresses,Set<BusinessEntity> businessEntities,String siigoCode) {
		this.id = id;
		this.region = region;
		this.name = name;
		this.addresses = addresses;
		this.businessEntities = businessEntities;
		this.siigoCode = siigoCode;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
		@SequenceGenerator(name = "pk_sequence", sequenceName = "city_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "region_id", nullable = false)
	@NotNull
	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "siigo_code")	
	public String getSiigoCode() {
		return this.siigoCode;
	}

	public void setSiigoCode(String siigoCode) {
		this.siigoCode = siigoCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "city")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}
	@OneToMany(fetch=FetchType.LAZY, mappedBy="city")
    public Set<BusinessEntity> getBusinessEntities() {
        return this.businessEntities;
    }
    
    public void setBusinessEntities(Set<BusinessEntity> businessEntities) {
    	this.businessEntities = businessEntities;
    }

}
