package org.koghi.terranvm.entity;

// Generated 31/03/2011 02:49:33 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ConcepTemplate generated by hbm2java
 */
@Entity
@Table(name = "concep_template", schema = "public")
public class ConcepTemplate implements java.io.Serializable {

	private int id;
	private String name;
	private String printDescription;
	private String expression;
	private Boolean isContributionModule;
	private Boolean isEarlyPayment;
	private Integer documentType;
	

	public ConcepTemplate() {
	}

	public ConcepTemplate(int id) {
		this.id = id;
	}

	public ConcepTemplate(int id, String name, String printDescription, String expression, Boolean isContributionModule, Boolean isEarlyPayment, Integer documentType) {
		this.id = id;
		this.name = name;
		this.printDescription = printDescription;
		this.expression = expression;
		this.isContributionModule = isContributionModule;
		this.isEarlyPayment = isEarlyPayment;
		this.documentType = documentType;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "concep_template_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "print_description")
	public String getPrintDescription() {
		return this.printDescription;
	}

	public void setPrintDescription(String printDescription) {
		this.printDescription = printDescription;
	}

	@Column(name = "expression")
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@Column(name = "is_contribution_module")
	public Boolean getIsContributionModule() {
		return this.isContributionModule;
	}

	public void setIsContributionModule(Boolean isContributionModule) {
		this.isContributionModule = isContributionModule;
	}

	@Column(name = "is_early_payment")
	public Boolean getIsEarlyPayment() {
		return this.isEarlyPayment;
	}

	public void setIsEarlyPayment(Boolean isEarlyPayment) {
		this.isEarlyPayment = isEarlyPayment;
	}

	@Column(name = "document_type")
	public Integer getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(Integer documentType) {
		this.documentType = documentType;
	}

}
