package org.koghi.terranvm.entity;

// Generated 8/02/2011 12:27:40 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ConsecutiveCreditNotes generated by hbm2java
 */
@Entity
@Table(name = "consecutive_credit_notes", schema = "public")
public class ConsecutiveCreditNotes implements java.io.Serializable {

	private int id;
	private BusinessEntity businessEntity;
	private String prefix;
	private String suffix;
	private String siigoCode;
	
	private int min;

	public ConsecutiveCreditNotes() {
	}

	public ConsecutiveCreditNotes(int id, BusinessEntity businessEntity,
			int min) {
		this.id = id;
		this.businessEntity = businessEntity;
		
		this.min = min;
	}

	public ConsecutiveCreditNotes(int id, BusinessEntity businessEntity,
			String prefix, String suffix, String siigoCode, int min) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.prefix = prefix;
		this.suffix = suffix;
		this.siigoCode = siigoCode;
		
		this.min = min;
	}
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "consecutive_credit_notes_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_entity", nullable = false)
	@NotNull
	public BusinessEntity getBusinessEntity() {
		return this.businessEntity;
	}

	public void setBusinessEntity(BusinessEntity businessEntity) {
		this.businessEntity = businessEntity;
	}

	@Column(name = "prefix")
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "suffix")
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "siigo_code")
	public String getSiigoCode() {
		return this.siigoCode;
	}

	public void setSiigoCode(String siigoCode) {
		this.siigoCode = siigoCode;
	}

	
	@Column(name = "min", nullable = false)
	public int getMin() {
		return this.min;
	}

	public void setMin(int min) {
		this.min = min;
	}

}
