package org.koghi.terranvm.entity;

// Generated 12/07/2011 04:47:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.NotNull;

/**
 * ConsecutiveDailySiigo generated by hbm2java
 */
@Entity
@Table(name = "consecutive_daily_siigo", schema = "public")
public class ConsecutiveDailySiigo implements java.io.Serializable {

	private int id;
	private int project;
	private int consecutive;
	private Date date;
	private String type;

	public ConsecutiveDailySiigo() {
	}

	public ConsecutiveDailySiigo(int id, int project, int consecutive, Date date, String type) {
		this.id = id;
		this.project = project;
		this.consecutive = consecutive;
		this.date = date;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "consecutive_daily_siigo_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@NotNull
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "project", nullable = false)
	@NotNull
	public int getProject() {
		return this.project;
	}

	public void setProject(int project) {
		this.project = project;
	}

	@Column(name = "consecutive", nullable = false)
	@NotNull
	public int getConsecutive() {
		return this.consecutive;
	}

	public void setConsecutive(int consecutive) {
		this.consecutive = consecutive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	@NotNull
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "type", nullable = false)
	@NotNull
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
