package org.koghi.terranvm.entity;

// Generated 30/05/2011 02:12:04 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * ConsecutiveCollectionAccount generated by hbm2java
 */
@Entity
@Table(name = "consecutive_collection_account", schema = "public")
public class ConsecutiveCollectionAccount implements java.io.Serializable {

	private int id;
	private BusinessEntity businessEntity;
	private String suffix;
	private String prefix;
	private String siigoCode;
	private int min;
	private Set<ProjectProperty> projectProperties = new HashSet<ProjectProperty>(0);

	public ConsecutiveCollectionAccount() {
	}

	public ConsecutiveCollectionAccount(int id, BusinessEntity businessEntity, String siigoCode, int min) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.siigoCode = siigoCode;
		this.min = min;
	}

	public ConsecutiveCollectionAccount(int id, BusinessEntity businessEntity, String suffix, String prefix, String siigoCode, int min, Set<ProjectProperty> projectProperties) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.suffix = suffix;
		this.prefix = prefix;
		this.siigoCode = siigoCode;
		this.min = min;
		this.projectProperties = projectProperties;
	}

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "consecutive_collection_account_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_entity", nullable = false)
	@NotNull
	public BusinessEntity getBusinessEntity() {
		return this.businessEntity;
	}

	public void setBusinessEntity(BusinessEntity businessEntity) {
		this.businessEntity = businessEntity;
	}

	@Column(name = "suffix")
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "prefix")
	public String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(String prefix) {
		this.prefix = prefix;
	}

	@Column(name = "siigo_code", nullable = false)
	@NotNull
	public String getSiigoCode() {
		return this.siigoCode;
	}

	public void setSiigoCode(String siigoCode) {
		this.siigoCode = siigoCode;
	}

	@Column(name = "min", nullable = false)
	public int getMin() {
		return this.min;
	}

	public void setMin(int min) {
		this.min = min;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "consecutiveCollectionAccount")
	public Set<ProjectProperty> getProjectProperties() {
		return this.projectProperties;
	}

	public void setProjectProperties(Set<ProjectProperty> projectProperties) {
		this.projectProperties = projectProperties;
	}

}
