package org.koghi.terranvm.entity;

// Generated 1/04/2011 11:39:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.validator.NotNull;

/**
 * ConstructionLicenses generated by hbm2java
 */
@Audited
@Entity
@Table(name = "construction_licenses", schema = "public")
public class ConstructionLicenses implements java.io.Serializable {

	private int id;
	private City city;
	private RealProperty realProperty;
	private String number;
	private String type;
	private Date dateLicense;
	private Integer numberCurating;
	private String description;

	public ConstructionLicenses() {
	}

	public ConstructionLicenses(int id, City city, RealProperty realProperty,
			String number, String type, Date dateLicense, int numberCurating) {
		this.id = id;
		this.city = city;
		this.realProperty = realProperty;
		this.number = number;
		this.type = type;
		this.dateLicense = dateLicense;
		this.numberCurating = numberCurating;
	}

	public ConstructionLicenses(int id, City city, RealProperty realProperty,
			String number, String type, Date dateLicense, int numberCurating,
			String description) {
		this.id = id;
		this.city = city;
		this.realProperty = realProperty;
		this.number = number;
		this.type = type;
		this.dateLicense = dateLicense;
		this.numberCurating = numberCurating;
		this.description = description;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "construction_licenses_pk_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "city_license", nullable = false)
	@NotNull
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@NotAudited
	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "realproperty", nullable = false)
	@NotNull
	public RealProperty getRealProperty() {
		return this.realProperty;
	}

	public void setRealProperty(RealProperty realProperty) {
		this.realProperty = realProperty;
	}

	@Column(name = "number", nullable = false)
	@NotNull
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "type", nullable = false)
	@NotNull
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_license", nullable = false, length = 13)
	@NotNull
	public Date getDateLicense() {
		return this.dateLicense;
	}

	public void setDateLicense(Date dateLicense) {
		this.dateLicense = dateLicense;
	}

	@Column(name = "number_curating", nullable = false)
	public Integer getNumberCurating() {
		return this.numberCurating;
	}

	public void setNumberCurating(Integer numberCurating) {
		this.numberCurating = numberCurating;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
