package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.validator.NotNull;

/**
 * Contact generated by hbm2java
 */
@Audited
@Entity
@Table(name = "contact", schema = "public")
public class Contact implements java.io.Serializable {

	private int id;
	private ContactType contactType;
	private String firstName;
	private String lastName;
	private String idNumber;
	private Set<RealPropertyContact> realPropertyContacts = new HashSet<RealPropertyContact>(0);
	private Set<BusinessEntityContact> businessEntityContacts = new HashSet<BusinessEntityContact>(0);
	private Set<PhoneNumber> phoneNumbers = new HashSet<PhoneNumber>(0);

	public Contact() {
	}

	public Contact(int id, ContactType contactType, String firstName, String lastName, String idNumber) {
		this.id = id;
		this.contactType = contactType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.idNumber = idNumber;
	}

	public Contact(int id, ContactType contactType, String firstName, String lastName, String idNumber, Set<RealPropertyContact> realPropertyContacts, Set<BusinessEntityContact> businessEntityContacts, Set<PhoneNumber> phoneNumbers) {
		this.id = id;
		this.contactType = contactType;
		this.firstName = firstName;
		this.lastName = lastName;
		this.idNumber = idNumber;
		this.realPropertyContacts = realPropertyContacts;
		this.businessEntityContacts = businessEntityContacts;
		this.phoneNumbers = phoneNumbers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
		@SequenceGenerator(name = "pk_sequence", sequenceName = "contact_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_type", nullable = false)
	@NotNull
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@NotAudited
	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	@Column(name = "first_name", nullable = false)
	@NotNull
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false)
	@NotNull
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "id_number", nullable = false)
	@NotNull
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(String idNumber) {
		this.idNumber = idNumber;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<RealPropertyContact> getRealPropertyContacts() {
		return this.realPropertyContacts;
	}

	public void setRealPropertyContacts(Set<RealPropertyContact> realPropertyContacts) {
		this.realPropertyContacts = realPropertyContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<BusinessEntityContact> getBusinessEntityContacts() {
		return this.businessEntityContacts;
	}

	public void setBusinessEntityContacts(Set<BusinessEntityContact> businessEntityContacts) {
		this.businessEntityContacts = businessEntityContacts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contact")
	public Set<PhoneNumber> getPhoneNumbers() {
		return this.phoneNumbers;
	}

	public void setPhoneNumbers(Set<PhoneNumber> phoneNumbers) {
		this.phoneNumbers = phoneNumbers;
	}

}
