package org.koghi.terranvm.entity;

// Generated Feb 28, 2011 11:23:53 AM by Hibernate Tools 3.4.0.Beta1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;

/**
 * ContributionModule generated by hbm2java
 */
@Entity
@Table(name = "contribution_module", schema = "public")
public class ContributionModule implements java.io.Serializable, Cloneable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RealProperty realProperty;
	private String name;
	private boolean apportionment;
	private Set<RentableUnitContribution> rentableUnitContributionsList = new HashSet<RentableUnitContribution>(0);

	public ContributionModule() {
	}

	public ContributionModule(int id, RealProperty realProperty, String name, boolean apportionment) {
		this.id = id;
		this.realProperty = realProperty;
		this.name = name;
		this.apportionment = apportionment;
	}

	public ContributionModule(int id, RealProperty realProperty, String name, Set<RentableUnitContribution> rentableUnitContributions, boolean apportionment) {
		this.id = id;
		this.realProperty = realProperty;
		this.name = name;
		this.apportionment = apportionment;
		this.rentableUnitContributionsList = rentableUnitContributions;
	}
	

	@Override
	public Object clone(){
		
		try {
            return super.clone();
        }
        catch (CloneNotSupportedException e) {
            // This should never happen
            throw new InternalError(e.toString());
        }
        
	}


	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "contribution_module_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "real_property", nullable = false)
	@NotNull
	public RealProperty getRealProperty() {
		return this.realProperty;
	}

	public void setRealProperty(RealProperty realProperty) {
		this.realProperty = realProperty;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	@Column(name = "apportionment", nullable = false)
	public boolean isApportionment() {
		return this.apportionment;
	}

	public void setApportionment(boolean apportionment) {
		this.apportionment = apportionment;
	}
	
	@Transient
	public List<RentableUnitContribution> getRentableUnitContributions() {
		return new ArrayList<RentableUnitContribution>(rentableUnitContributionsList);
	}

	public void setRentableUnitContributions(List<RentableUnitContribution> rentableUnitContributions) {
		this.rentableUnitContributionsList = new HashSet<RentableUnitContribution> (rentableUnitContributions);
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "contributionModule", cascade = CascadeType.ALL)
	public Set<RentableUnitContribution> getRentableUnitContributionsList() {
		return rentableUnitContributionsList;
	}

	public void setRentableUnitContributionsList(
			Set<RentableUnitContribution> rentableUnitContributionsList) {
		this.rentableUnitContributionsList = rentableUnitContributionsList;
	}
}
