package org.koghi.terranvm.entity;

// Generated 28/03/2012 04:59:37 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.envers.NotAudited;
import org.hibernate.envers.RelationTargetAuditMode;
import org.hibernate.validator.NotNull;

/**
 * CounterTemplateHasRetentionRateAccount generated by hbm2java
 */
@Entity
@Table(name = "counter_template_has_retention_rate_account", schema = "public")
public class CounterTemplateHasRetentionRateAccount implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private CounterConfigurationTamplate counterConfigurationTamplate;
	private RetentionRateAccount retentionRateAccountId;

	public CounterTemplateHasRetentionRateAccount() {
	}

	public CounterTemplateHasRetentionRateAccount(int id, CounterConfigurationTamplate counterConfigurationTamplate,RetentionRateAccount  retentionRateAccountId) {
		this.id = id;
		this.counterConfigurationTamplate = counterConfigurationTamplate;
		this.retentionRateAccountId = retentionRateAccountId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "counter_template_has_retention_rate_account_id_sec", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "counter_configuration_template_id", nullable = false)
	@NotNull
	public CounterConfigurationTamplate getCounterConfigurationTamplate() {
		return this.counterConfigurationTamplate;
	}

	public void setCounterConfigurationTamplate(CounterConfigurationTamplate counterConfigurationTamplate) {
		this.counterConfigurationTamplate = counterConfigurationTamplate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "retention_rate_account_id")
	@Audited(targetAuditMode = RelationTargetAuditMode.NOT_AUDITED)
	@NotAudited
	public RetentionRateAccount getRetentionRateAccountId() {
		return this.retentionRateAccountId;
	}

	public void setRetentionRateAccountId(RetentionRateAccount retentionRateAccountId) {
		this.retentionRateAccountId = retentionRateAccountId;
	}

}
