package org.koghi.terranvm.entity;

// Generated Apr 10, 2011 3:33:33 PM by Hibernate Tools 3.4.0.CR1

import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.NotNull;

/**
 * CreditNote generated by hbm2java
 */
@Entity
@Table(name = "credit_note", schema = "public")
public class CreditNote implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private double value;
	private String consecutive;
	private Date creditNoteDate;
	private String reason;
	private String userEmail;
	private Set<InvoiceConcept> invoiceConcepts = new HashSet<InvoiceConcept>(0);

	public CreditNote() {
	}

	public CreditNote(int id, double value, String consecutive, Date creditNoteDate , String reason, Set<InvoiceConcept> invoiceConcepts, String userEmail) {
		this.id = id;
		this.value = value;
		this.consecutive = consecutive;
		this.creditNoteDate = creditNoteDate;
		this.reason = reason;
		this.invoiceConcepts = invoiceConcepts;
		this.userEmail = userEmail;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "credit_note_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Column(name = "consecutive", nullable = false)
	@NotNull
	public String getConsecutive() {
		return this.consecutive;
	}

	public void setConsecutive(String consecutive) {
		this.consecutive = consecutive;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "credit_note_date", nullable = false, length = 13)
	@NotNull
	public Date getCreditNoteDate() {
		return this.creditNoteDate;
	}

	public void setCreditNoteDate(Date creditNoteDate) {
		this.creditNoteDate = creditNoteDate;
	}
	
	@Column(name = "reason", nullable = false)
	@NotNull
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "creditNote")
	public Set<InvoiceConcept> getInvoiceConcepts() {
		return this.invoiceConcepts;
	}

	public void setInvoiceConcepts(Set<InvoiceConcept> invoiceConcepts) {
		this.invoiceConcepts = invoiceConcepts;
	}
	@Column(name = "user_email")
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	public String values(){
		DecimalFormat formato = new DecimalFormat("#,###,###.00");
		return formato.format(this.value);
	}
	
}
