package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * EconomicActivity generated by hbm2java
 */
@Entity
@Table(name = "economic_activity", schema = "public")
public class EconomicActivity implements java.io.Serializable {

	private EconomicSector economicSector;
	private String name;
	private String description;
	private String code;
	private Set<BusinessEntity> businessEntities = new HashSet<BusinessEntity>(0);

	public EconomicActivity() {
	}

	public EconomicActivity(EconomicSector economicSector, String name, String code) {
		this.economicSector = economicSector;
		this.name = name;
		this.code = code;
	}

	public EconomicActivity(EconomicSector economicSector, String name, String description, String code, Set<BusinessEntity> businessEntities) {
		this.economicSector = economicSector;
		this.name = name;
		this.description = description;
		this.code = code;
		this.businessEntities = businessEntities;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "economic_sector", nullable = false)
	@NotNull
	public EconomicSector getEconomicSector() {
		return this.economicSector;
	}

	public void setEconomicSector(EconomicSector economicSector) {
		this.economicSector = economicSector;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Id
	@Column(name = "code", nullable = false)
	@NotNull
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "economicActivity")
	public Set<BusinessEntity> getBusinessEntities() {
		return this.businessEntities;
	}

	public void setBusinessEntities(Set<BusinessEntity> businessEntities) {
		this.businessEntities = businessEntities;
	}

}
