package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * EconomicSector generated by hbm2java
 */
@Entity
@Table(name = "economic_sector", schema = "public")
public class EconomicSector implements java.io.Serializable {

	private int id;
	private String name;
	private String description;
	private Set<EconomicActivity> economicActivities = new HashSet<EconomicActivity>(0);

	public EconomicSector() {
	}

	public EconomicSector(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public EconomicSector(int id, String name, String description, Set<EconomicActivity> economicActivities) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.economicActivities = economicActivities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
		@SequenceGenerator(name = "pk_sequence", sequenceName = "economic_sector_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "economicSector")
	public Set<EconomicActivity> getEconomicActivities() {
		return this.economicActivities;
	}

	public void setEconomicActivities(Set<EconomicActivity> economicActivities) {
		this.economicActivities = economicActivities;
	}

}
