package org.koghi.terranvm.entity;

// Generated 2/03/2011 03:36:38 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * Features generated by hbm2java
 */
@Entity
@Table(name = "features", schema = "public")
public class Features implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String page;
	private Set<Role> rol = new HashSet<Role>(0);
	private Set<Action> actions = new HashSet<Action>(0);

	public Features() {
	}

	public Features(int id, String page) {
		this.id = id;
		this.page = page;
	}

	public Features(int id, String page, Set<Role> rol, Set<Action> actions) {
		this.id = id;
		this.page = page;
		this.rol = rol;
		this.actions = actions;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "page", nullable = false)
	@NotNull
	public String getPage() {
		return this.page;
	}

	public void setPage(String page) {
		this.page = page;
	}

	
	@ManyToMany(targetEntity = org.koghi.terranvm.entity.Role.class, cascade = { CascadeType.PERSIST, CascadeType.MERGE }, fetch = FetchType.LAZY)
	@JoinTable(name = "ROLE_FEATURES", joinColumns = @JoinColumn(name = "FEATURES"), inverseJoinColumns = @JoinColumn(name = "ROLE"))
	public Set<Role> getRol() {
		return rol;
	}

	public void setRol(Set<Role> rol) {
		this.rol = rol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "features")
	public Set<Action> getActions() {
		return this.actions;
	}

	public void setActions(Set<Action> actions) {
		this.actions = actions;
	}

}
