package org.koghi.terranvm.entity;

// Generated 12/03/2011 02:09:31 PM by Hibernate Tools 3.4.0.Beta1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;

/**
 * GroupCache generated by hbm2java
 */
@Entity
@Table(name = "group_cache", schema = "public")
public class GroupCache implements java.io.Serializable {

	/**
     * 
     */
    private static final long serialVersionUID = 1L;
    private int id;
	private int realProperty;
	private int billed;
	private int biller;
	private boolean grouped;
	private boolean groupedIntoPeriod;
	private Address address;
	private String billingPeriod;
	private int billingCount;
	private int billingDocumentType;
	private List<Invoice> invoices; 

	public GroupCache() {
	}

	public GroupCache(int id, int realProperty, int billed, int biller,
			boolean grouped, boolean groupedIntoPeriod, Address address, String billingPeriod, int billingCount) {
		this.id = id;
		this.realProperty = realProperty;
		this.billed = billed;
		this.biller = biller;
		this.grouped = grouped;
		this.groupedIntoPeriod = groupedIntoPeriod;
		this.address = address;
		this.billingPeriod = billingPeriod;
		this.billingCount = billingCount;
	}

	@Id
	@SequenceGenerator(name = "pk_sequence", sequenceName = "group_cache_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "real_property", nullable = false)
	public int getRealProperty() {
		return this.realProperty;
	}

	public void setRealProperty(int realProperty) {
		this.realProperty = realProperty;
	}

	@Column(name = "billed", nullable = false)
	public int getBilled() {
		return this.billed;
	}

	public void setBilled(int billed) {
		this.billed = billed;
	}

	@Column(name = "biller", nullable = false)
	public int getBiller() {
		return this.biller;
	}

	public void setBiller(int biller) {
		this.biller = biller;
	}

	@Column(name = "grouped", nullable = false)
	public boolean isGrouped() {
		return this.grouped;
	}
	
	public void setGrouped(boolean grouped) {
		this.grouped = grouped;
	}
	
	@Column(name = "grouped_into_period", nullable = false)
	public boolean isGroupedIntoPeriod() {
		return this.groupedIntoPeriod;
	}

	public void setGroupedIntoPeriod(boolean groupedIntoPeriod) {
		this.groupedIntoPeriod = groupedIntoPeriod;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address", nullable = false)	
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "billing_period", nullable = false)
	@NotNull
	public String getBillingPeriod() {
		return this.billingPeriod;
	}

	public void setBillingPeriod(String billingPeriod) {
		this.billingPeriod = billingPeriod;
	}

	@Column(name = "billing_count", nullable = false)
	public int getBillingCount() {
		return this.billingCount;
	}

	public void setBillingCount(int billingCount) {
		this.billingCount = billingCount;
	}

	@Column(name = "billing_document_type")
	public int getBillingDocumentType() {
		return billingDocumentType;
	}

	public void setBillingDocumentType(int billingDocumentType) {
		this.billingDocumentType = billingDocumentType;
	}

	@Transient
	public List<Invoice> getInvoices() {
		return invoices;
	}

	public void setInvoices(List<Invoice> invoices) {
		this.invoices = invoices;
	}
}
