package org.koghi.terranvm.entity;

//Generated 2/04/2011 06:00:41 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;

/**
 * Increased generated by hbm2java
 */
@Entity
@Table(name = "increased", schema = "public")
public class Increased implements java.io.Serializable {

	private int id;
	private int periodicityType;
	private Integer periodicity;
	private Date nextIncreased;
	private Date lastCalculated;
	private String expression;
	private Set<Concept> concepts = new HashSet<Concept>(0);
	

	public Increased() {
	}

	public Increased(int id, int periodicityType, Integer periodicity) {
		this.id = id;
		this.periodicityType = periodicityType;
		this.periodicity = periodicity;
	}

	public Increased(int id, int periodicityType, Integer periodicity, Date nextIncreased, String expression, Set<Concept> concepts) {
		this.id = id;
		this.periodicityType = periodicityType;
		this.periodicity = periodicity;
		this.nextIncreased = nextIncreased;
		this.expression = expression;
		this.concepts = concepts;
		
	}

	@Id
	@SequenceGenerator(name = "pk_sequence", sequenceName = "increased_increment_seg", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "periodicity_type", nullable = false)
	public int getPeriodicityType() {
		return this.periodicityType;
	}

	public void setPeriodicityType(int periodicityType) {
		this.periodicityType = periodicityType;
	}

	@Column(name = "periodicity", nullable = false)
	public Integer getPeriodicity() {
		return this.periodicity;
	}

	public void setPeriodicity(Integer periodicity) {
		this.periodicity = periodicity;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "next_increased", length = 13)
	public Date getNextIncreased() {
		return this.nextIncreased;
	}
		
	@Temporal(TemporalType.DATE)
	@Column(name = "last_calculated", length = 13)
	public Date getLastCalculated() {
		return lastCalculated;
	}

	public void setLastCalculated(Date lastCalculated) {
		this.lastCalculated = lastCalculated;
	}

	public void setNextIncreased(Date nextIncreased) {
		this.nextIncreased = nextIncreased;
	}

	@Column(name = "expression", length = 2000)
	@Length(max = 2000)
	public String getExpression() {
		return this.expression;
	}

	public void setExpression(String expression) {
		this.expression = expression;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "increased")
	public Set<Concept> getConcepts() {
		return this.concepts;
	}

	public void setConcepts(Set<Concept> concepts) {
		this.concepts = concepts;
	}

	
}
