package org.koghi.terranvm.entity;

// Generated Feb 4, 2011 8:33:17 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * InvoiceStatus generated by hbm2java
 */
@Entity
@Table(name = "invoice_status", schema = "public")
public class InvoiceStatus implements java.io.Serializable {
	
	public static final int STATUS_VIGENTE= 1;
	public static final int STATUS_SOLICITUD_DE_REVERSION= 2;
	public static final int STATUS_REVERSION_APROBADA= 3;
	public static final int STATUS_REVERSADA= 4;
	public static final int STATUS_FACTURAS_NO_APROBADAS = 5;
	
	public static final String PERMISSION_VIGENTE="valid";
	public static final String PERMISSION_SOLICITUD_REVERSION="reversal_request";
	public static final String PERMISSION_REVERSION_APROBADA="approved_reversal";
	public static final String PERMISSION_REVERSADA="reversible";
	public static final String PERMISSION_FACTURAS_NO_APROBADAS="unapproved_invoices";
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public InvoiceStatus() {
	}

	public InvoiceStatus(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public InvoiceStatus(int id, String name, Set<Invoice> invoices) {
		this.id = id;
		this.name = name;
		this.invoices = invoices;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invoiceStatus")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
