package org.koghi.terranvm.entity;

// Generated 20/05/2011 03:13:13 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * MakerCheckerXProject generated by hbm2java
 */
@Entity
@Table(name = "maker_checker_x_project", schema = "public")
public class MakerCheckerXProject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private MakerChecker makerChecker;
	private Project project;

	public MakerCheckerXProject() {
	}

	public MakerCheckerXProject(int id, MakerChecker makerChecker,
			Project project) {
		this.id = id;
		this.makerChecker = makerChecker;
		this.project = project;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "maker_ckecker", nullable = false)
	@NotNull
	public MakerChecker getMakerChecker() {
		return this.makerChecker;
	}

	public void setMakerChecker(MakerChecker makerChecker) {
		this.makerChecker = makerChecker;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project", nullable = false)
	@NotNull
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
