package org.koghi.terranvm.entity;

// Generated 14/01/2011 08:24:49 AM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.validator.NotNull;

/**
 * MakerChecker generated by hbm2java
 */
@Entity
@Table(name = "maker_checker", schema = "public")
public class MakerChecker implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private int id;
	private byte[] object;
	private int objectId;
	private String className;
	private Integer conceptId;
	private String description;
	private Set<Project> makerCheckerXProjects = new HashSet<Project>(0);

	public MakerChecker() {
	}

	public MakerChecker(int id, byte[] object, String className, String description, Set<Project> makerCheckerXProjects) {
		this.id = id;
		this.object = object;
		this.className = className;
		this.description = description;
		this.makerCheckerXProjects = makerCheckerXProjects;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "maker_checker_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "object", nullable = false)
	@NotNull
	public byte[] getObject() {
		return this.object;
	}

	public void setObject(byte[] object) {
		this.object = object;
	}

	@Column(name = "class_name", nullable = false)
	@NotNull
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "object_id", nullable = false)
	@NotNull
	public int getObjectId() {
		return objectId;
	}

	public void setObjectId(int objectId) {
		this.objectId = objectId;
	}

	@Column(name = "concept_id", nullable = true)
	public Integer getConceptId() {
		return conceptId;
	}

	public void setConceptId(Integer conceptId) {
		this.conceptId = conceptId;
	}
	
	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@ManyToMany(targetEntity = org.koghi.terranvm.entity.Project.class, cascade = { CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REMOVE }, fetch = FetchType.LAZY)
	@JoinTable(name = "maker_checker_x_project", joinColumns = @JoinColumn(name = "maker_ckecker"), inverseJoinColumns = @JoinColumn(name = "project"))
	public Set<Project> getMakerCheckerXProjects() {
		return this.makerCheckerXProjects;
	}

	public void setMakerCheckerXProjects(Set<Project> makerCheckerXProjects) {
		this.makerCheckerXProjects = makerCheckerXProjects;
	}
}
