package org.koghi.terranvm.entity;

// Generated 1/03/2011 03:19:36 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.NotNull;

/**
 * ObjectOfContract generated by hbm2java
 */
@Entity
@Table(name = "object_of_contract", schema = "public")
@Audited
public class ObjectOfContract implements java.io.Serializable {
	
	public static final int OBJECT_REALPROPERTY= 1;
	public static final int OBJECT_RENTABLEUNIT= 2;
	public static final int OBJECT_SERVICE= 3;

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String description;
	private Set<ProjectProperty> projectProperties = new HashSet<ProjectProperty>(0);

	public ObjectOfContract() {
	}

	public ObjectOfContract(int id, String description) {
		this.id = id;
		this.description = description;
	}

	public ObjectOfContract(int id, String description, Set<ProjectProperty> projectProperties) {
		this.id = id;
		this.description = description;
		this.projectProperties = projectProperties;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "description", nullable = false)
	@NotNull
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectOfContract")
	public Set<ProjectProperty> getProjectProperties() {
		return this.projectProperties;
	}

	public void setProjectProperties(Set<ProjectProperty> projectProperties) {
		this.projectProperties = projectProperties;
	}

}
