package org.koghi.terranvm.entity;

// Generated 11/05/2011 06:56:29 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * PayFormType generated by hbm2java
 */
@Entity
@Table(name = "pay_form_type", schema = "public")
public class PayFormType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final int AVAIBLE_PAY_FORM = 1;
	public static final int CHECK_PAY_FORM = 2;
	
	private int id;
	private String name;
	private Set<Recover> recovers = new HashSet<Recover>(0);

	public PayFormType() {
	}

	public PayFormType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public PayFormType(int id, String name, Set<Recover> recovers) {
		this.id = id;
		this.name = name;
		this.recovers = recovers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payFormType")
	public Set<Recover> getRecovers() {
		return this.recovers;
	}

	public void setRecovers(Set<Recover> recovers) {
		this.recovers = recovers;
	}

}
