package org.koghi.terranvm.entity;

// Generated 10/06/2011 10:05:45 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

/**
 * File generated by hbm2java
 */
@Entity
@DiscriminatorValue("ATTACH_PDF_HT")
public class PDFFile extends File{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private ProjectProperty projectProperty;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project_property")
	public ProjectProperty getProjectProperty() {
		return this.projectProperty;
	}

	public void setProjectProperty(ProjectProperty projectProperty) {
		this.projectProperty = projectProperty;
	}

}
