package org.koghi.terranvm.entity;

// Generated 05-ene-2011 12:42:23 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.envers.Audited;
import org.hibernate.validator.NotNull;

/**
 * PhoneNumber generated by hbm2java
 */
@Audited
@Entity
@Table(name = "phone_number", schema = "public")
public class PhoneNumber implements java.io.Serializable {

	private int id;
	private BusinessEntity businessEntity;
	private Contact contact;
	private String number;
	private String indicative;
	private String extension;

	public PhoneNumber() {
	}

	public PhoneNumber(int id, BusinessEntity businessEntity, Contact contact, String number) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.contact = contact;
		this.number = number;
	}

	public PhoneNumber(int id, BusinessEntity businessEntity, Contact contact, String number, String indicative, String extension) {
		this.id = id;
		this.businessEntity = businessEntity;
		this.contact = contact;
		this.number = number;
		this.indicative = indicative;
		this.extension = extension;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
		@SequenceGenerator(name = "pk_sequence", sequenceName = "phone_number_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "business_entity")
	public BusinessEntity getBusinessEntity() {
		return this.businessEntity;
	}

	public void setBusinessEntity(BusinessEntity businessEntity) {
		this.businessEntity = businessEntity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact")
	public Contact getContact() {
		return this.contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	@Column(name = "number", nullable = false)
	@NotNull
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Column(name = "indicative")
	public String getIndicative() {
		return this.indicative;
	}

	public void setIndicative(String indicative) {
		this.indicative = indicative;
	}

	@Column(name = "extension")
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}
	
	@Override
	public String toString() {
		String res = "";
		if (indicative!=null && !indicative.isEmpty())
			res += "(" + indicative + ") ";
		res += number;
		
		if (extension != null && !extension.isEmpty() )
			res += " Ext. " + extension;
		return res;
	}

}
