package org.koghi.terranvm.entity;

// Generated 2/03/2011 03:36:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * ProjectUser generated by hbm2java
 */
@Entity
@Table(name = "project_user", schema = "public")
public class ProjectUser implements java.io.Serializable {

	private int id;
	private User_Terranvm user;
	private Project project;

	public ProjectUser() {
	}

	public ProjectUser(int id, User_Terranvm user, Project project) {
		this.id = id;
		this.user = user;
		this.project = project;
	}

	@Id
	@SequenceGenerator(name = "pk_sequence", sequenceName = "project_user_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_terranvm", nullable = false)
	@NotNull
	public User_Terranvm getUser() {
		return this.user;
	}

	public void setUser(User_Terranvm user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project", nullable = false)
	@NotNull
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

}
