package org.koghi.terranvm.entity;

// Generated 29/03/2011 05:35:37 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * RecoverConcept generated by hbm2java
 */
@Entity
@Table(name = "recover_concept", schema = "public")
public class RecoverConcept implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private Recover recover;
	private InvoiceConcept invoiceConcept;
	private double value;

	public RecoverConcept() {
	}

	public RecoverConcept(int id, Recover recover, InvoiceConcept invoiceConcept, double value) {
		this.id = id;
		this.recover = recover;
		this.invoiceConcept = invoiceConcept;
		this.value = value;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "recover_concept_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "recover", nullable = false)
	@NotNull
	public Recover getRecover() {
		return this.recover;
	}

	public void setRecover(Recover recover) {
		this.recover = recover;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
	@JoinColumn(name = "invoice_concept", nullable = false)
	@NotNull
	public InvoiceConcept getInvoiceConcept() {
		return this.invoiceConcept;
	}

	public void setInvoiceConcept(InvoiceConcept invoiceConcept) {
		this.invoiceConcept = invoiceConcept;
	}

	@Column(name = "value", nullable = false, precision = 17, scale = 17)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
