package org.koghi.terranvm.entity;

// Generated 16/05/2011 12:08:50 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.validator.NotNull;

/**
 * RecoverClosure generated by hbm2java
 */
@Entity
@Table(name = "recover_closure", schema = "public")
@Audited
public class RecoverClosure implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**Arreglo que representa los meses en español. La posición corresponde al mes que se hace referencia según la clase Calendar.
	 * Ejemplo, para obtener el mes de febrero Months[Calendar.FEBRUARY]
	**/
	public static final String[] MONTHS = { "ENERO",
											"FEBRERO",
											"MARZO",
											"ABRIL",
											"MAYO",
											"JUNIO",
											"JULIO",
											"AGOSTO",
											"SEPTIEMBRE",
											"OCTUBRE",
											"NOVIEMBRE",
											"DICIEMBRE" 
											};
	
	
	private int id;
	private Project project;
	private Date date;
	private int month;
	private Date closureDate;

	public RecoverClosure() {
	}

	public RecoverClosure(int id, Project project, Date date, int month, Date closureDate) {
		this.id = id;
		this.project = project;
		this.date = date;
		this.month = month;
		this.closureDate = closureDate;
	}

	@Id
	@SequenceGenerator(name = "pk_sequence", sequenceName = "recover_closure_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project", nullable = false)
	@NotNull
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	@NotNull
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	@Column(name = "month", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "closure_date", nullable = false, length = 13)
	@NotNull
	public Date getClosureDate() {
		return this.closureDate;
	}

	public void setClosureDate(Date closureDate) {
		this.closureDate = closureDate;
	}

}
