package org.koghi.terranvm.entity;

// Generated 11/03/2011 12:00:10 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * RentableUnitType generated by hbm2java
 */
@Entity
@Table(name = "rentable_unit_type", schema = "public")
public class RentableUnitType implements java.io.Serializable {

	private int id;
	private String type;
	private Set<RentableUnit> rentableUnits = new HashSet<RentableUnit>(0);
	private Set<RentableUnit> rentableUnits_1 = new HashSet<RentableUnit>(0);

	public RentableUnitType() {
	}

	public RentableUnitType(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public RentableUnitType(int id, String type,
			Set<RentableUnit> rentableUnits, Set<RentableUnit> rentableUnits_1) {
		this.id = id;
		this.type = type;
		this.rentableUnits = rentableUnits;
		this.rentableUnits_1 = rentableUnits_1;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false)
	@NotNull
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rentableUnitType")
	public Set<RentableUnit> getRentableUnits() {
		return this.rentableUnits;
	}

	public void setRentableUnits(Set<RentableUnit> rentableUnits) {
		this.rentableUnits = rentableUnits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rentableUnitType")
	public Set<RentableUnit> getRentableUnits_1() {
		return this.rentableUnits_1;
	}

	public void setRentableUnits_1(Set<RentableUnit> rentableUnits_1) {
		this.rentableUnits_1 = rentableUnits_1;
	}

}
