package org.koghi.terranvm.entity;

// Generated 22/03/2011 05:11:14 PM by Hibernate Tools 3.4.0.Beta1

import java.text.DecimalFormat;
import java.util.Locale;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.envers.Audited;
import org.hibernate.validator.NotNull;

/**
 * Sales generated by hbm2java
 */
@Audited
@Entity
@Table(name = "sales", schema = "public")
public class Sales implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private RentableUnit rentableUnit;
	private SalesPeriod salesPeriod;
	private double value;
	private BusinessEntity businessEntity;

	public Sales() {
	}

	public Sales(int id, RentableUnit rentableUnit, SalesPeriod salesPeriod,
			double value) {
		this.id = id;
		this.rentableUnit = rentableUnit;
		this.salesPeriod = salesPeriod;
		this.value = value;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "sales_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rentable_unit", nullable = false)
	@NotNull
	public RentableUnit getRentableUnit() {
		return this.rentableUnit;
	}

	public void setRentableUnit(RentableUnit rentableUnit) {
		this.rentableUnit = rentableUnit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sales_period", nullable = false)
	@NotNull
	public SalesPeriod getSalesPeriod() {
		return this.salesPeriod;
	}

	public void setSalesPeriod(SalesPeriod salesPeriod) {
		this.salesPeriod = salesPeriod;
	}

	@Column(name = "value", nullable = false, precision = 17, scale = 17)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Transient
	public String getFormatterValue(){
		Locale.setDefault(Locale.ENGLISH);
		DecimalFormat formatter = new DecimalFormat("0.00");
		return formatter.format(getValue());
	}
	
	@Transient
	public void setFormatterValue(String value){
		Locale.setDefault(Locale.ENGLISH);
		try{
			setValue(Double.parseDouble(value));
		}catch (Exception e) {
			System.out.println("El dato ingresado no es número.");
			setValue(0);
		}
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "lessee")
	public BusinessEntity getBusinessEntity() {
		return this.businessEntity;
	}

	public void setBusinessEntity(BusinessEntity businessEntity) {
		this.businessEntity = businessEntity;
	}
}
