package org.koghi.terranvm.entity;

// Generated 1/04/2011 11:39:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;
import org.hibernate.validator.NotNull;

/**
 * SegmentStage generated by hbm2java
 */
@Audited
@Entity
@Table(name = "segment_stage", schema = "public")
public class SegmentStage implements java.io.Serializable {

	private int id;
	private RealProperty realProperty;
	private String tramo;
	private double percentage;
	private Date datePurchase;

	public SegmentStage() {
	}

	public SegmentStage(int id, RealProperty realProperty, String tramo,
			double percentage, Date datePurchase) {
		this.id = id;
		this.realProperty = realProperty;
		this.tramo = tramo;
		this.percentage = percentage;
		this.datePurchase = datePurchase;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@SequenceGenerator(name = "pk_sequence", sequenceName = "segment_stage_pk_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "realproperty", nullable = false)
	@NotNull
	public RealProperty getRealProperty() {
		return this.realProperty;
	}

	public void setRealProperty(RealProperty realProperty) {
		this.realProperty = realProperty;
	}

	@Column(name = "tramo", nullable = false)
	@NotNull
	public String getTramo() {
		return this.tramo;
	}

	public void setTramo(String tramo) {
		this.tramo = tramo;
	}

	@Column(name = "percentage", nullable = false, precision = 17, scale = 17)
	public double getPercentage() {
		return this.percentage;
	}

	public void setPercentage(double percentage) {
		this.percentage = percentage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_purchase", nullable = false, length = 13)
	@NotNull
	public Date getDatePurchase() {
		return this.datePurchase;
	}

	public void setDatePurchase(Date datePurchase) {
		this.datePurchase = datePurchase;
	}

}
