package org.koghi.terranvm.entity;

// Generated 10/06/2011 10:05:45 AM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

/**
 * File generated by hbm2java
 */
@Entity
@DiscriminatorValue("SIIGO")
public class SIGGOFile extends File{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	

}
