package org.koghi.terranvm.entity;

// Generated 18/03/2011 07:33:11 PM by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxConfiguration generated by hbm2java
 */
@Entity
@Table(name = "tax_configuration", schema = "public")
public class TaxConfiguration implements java.io.Serializable {

	private int id;
	private Taxliabilities taxliabilitiesByBilled;
	private Taxliabilities taxliabilitiesByBiller;
	private RetentionRate retentionRate;

	public TaxConfiguration() {
	}

	public TaxConfiguration(int id) {
		this.id = id;
	}

	public TaxConfiguration(int id, Taxliabilities taxliabilitiesByBilled, Taxliabilities taxliabilitiesByBiller, RetentionRate retentionRate) {
		this.id = id;
		this.taxliabilitiesByBilled = taxliabilitiesByBilled;
		this.taxliabilitiesByBiller = taxliabilitiesByBiller;
		this.retentionRate = retentionRate;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "billed")
	public Taxliabilities getTaxliabilitiesByBilled() {
		return this.taxliabilitiesByBilled;
	}

	public void setTaxliabilitiesByBilled(Taxliabilities taxliabilitiesByBilled) {
		this.taxliabilitiesByBilled = taxliabilitiesByBilled;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "biller")
	public Taxliabilities getTaxliabilitiesByBiller() {
		return this.taxliabilitiesByBiller;
	}

	public void setTaxliabilitiesByBiller(Taxliabilities taxliabilitiesByBiller) {
		this.taxliabilitiesByBiller = taxliabilitiesByBiller;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "retention_rate")
	public RetentionRate getRetentionRate() {
		return this.retentionRate;
	}

	public void setRetentionRate(RetentionRate retentionRate) {
		this.retentionRate = retentionRate;
	}

}
