package org.koghi.terranvm.entity;

// Generated 18/03/2011 07:33:11 PM by Hibernate Tools 3.4.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;

/**
 * Taxliabilities generated by hbm2java
 */
@Entity
@Table(name = "taxliabilities", schema = "public")
public class Taxliabilities implements java.io.Serializable {

	private int id;
	private String name;
	private Set<TaxConfiguration> taxConfigurationsForBilled = new HashSet<TaxConfiguration>(0);	
	private Set<TaxConfiguration> taxConfigurationsForBiller = new HashSet<TaxConfiguration>(0);	

	public Taxliabilities() {
	}

	public Taxliabilities(int id) {
		this.id = id;
	}

	public Taxliabilities(int id, String name, Set<TaxConfiguration> taxConfigurationsForBilled, Set<TaxConfiguration> taxConfigurationsForBiller) {
		this.id = id;
		this.name = name;
		this.taxConfigurationsForBilled = taxConfigurationsForBilled;		
		this.taxConfigurationsForBiller = taxConfigurationsForBiller;
		
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	@Length(max = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxliabilitiesByBilled")
	public Set<TaxConfiguration> getTaxConfigurationsForBilled() {
		return this.taxConfigurationsForBilled;
	}

	public void setTaxConfigurationsForBilled(Set<TaxConfiguration> taxConfigurationsForBilled) {
		this.taxConfigurationsForBilled = taxConfigurationsForBilled;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxliabilitiesByBiller")
	public Set<TaxConfiguration> getTaxConfigurationsForBiller() {
		return this.taxConfigurationsForBiller;
	}

	public void setTaxConfigurationsForBiller(Set<TaxConfiguration> taxConfigurationsForBiller) {
		this.taxConfigurationsForBiller = taxConfigurationsForBiller;
	}

	
}
