package org.koghi.terranvm.entity;

// Generated 10/05/2011 03:57:26 PM by Hibernate Tools 3.4.0.CR1

import java.util.Calendar;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;

/**
 * UsuryRate generated by hbm2java
 */
@Entity
@Table(name = "usury_rate", schema = "public")
public class UsuryRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2590058406496551617L;
	private int id;
	private double value;
	private Date date;
	private Boolean rateUsed;
	
	
	public Date showdate;

	public UsuryRate() {
	}

	public UsuryRate(int id, double value, Date date) {
		this.id = id;
		this.value = value;
		this.date = date;
	}
	
	public UsuryRate(int id, double value, Date date, Boolean rateUsed) {
		this.id = id;
		this.value = value;
		this.date = date;
		this.rateUsed = rateUsed;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
    @SequenceGenerator(name = "pk_sequence", sequenceName = "usury_rate_id_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pk_sequence")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "value", nullable = false, precision = 17, scale = 17)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 13)
	@NotNull
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
	
	@Transient
	public double getUsuryValue(){
		return (this.getValue()*100);
	}
	
	@Transient
	public void setUsuryValue(double value){
		this.setValue(value / 100);
	}
	
	@Transient
	public Date getUsuryDate() {
		Calendar calendar = Calendar.getInstance();
		this.date = calendar.getTime();
		return this.date;
	}

	@Transient
	public void setUsuryDate(Date date) {
		this.date = date;
	}

	@Transient
	public double getValueDiary(){
		double a = new Double(1);
		double b = new Double(360);
		double p = new Double(a/b);
		return (Math.pow(1+getValue(), p)) - 1;
	}
	
	@Column(name = "rate_used")
	public Boolean getRateUsed() {
		return this.rateUsed;
	}

	public void setRateUsed(Boolean rateUsed) {
		this.rateUsed = rateUsed;
	}

}
